// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydysvpsifsixhrczheqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkeXN2cHNpZnNpeGhyY3poZXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NDg0ODIsImV4cCI6MjA1NDUyNDQ4Mn0.of8uMlx2ipeOnYUYcBlHAb7IBVBywJnV3JUWtc07Q_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);